version: 2.1

orbs:
  node: circleci/node@4.0.0
  codecov: codecov/codecov@1.1.3

jobs:
  tests:
    docker:
      - image: circleci/node:14.15.5-browsers
    steps:
      - checkout
      - node/install-yarn
      - run:
          name: Show Node version
          command: |
            node --version
            yarn --version
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run lint in js
          command: yarn lintjs
      - run:
          name: Run lint in jsx
          command: yarn lintjsx
      - run:
          name: Run unit test with coverage
          command: yarn coverage
      - codecov/upload:
          file: coverage/*.json
      - run:
          name: Publish to Chromatic
          command: yarn chromatic --project-token=${CHROMATIC_TOKEN}
  versioning:
    docker:
      - image: circleci/node:14.15.5-browsers
    steps:
      - checkout
      - run:
          name: Check package version
          command: node scripts/check-versions DevJonh autoescola-nardini

workflows:
  ci:
    jobs:
      - tests
      - versioning:
          filters:
            branches:
              ignore: master
            tags:
              ignore: /.*/
