version: 2.1

orbs:
  node: circleci/node@4.0.0
  codecov: codecov/codecov@1.1.3

jobs:
  tests:
    docker:
      - image: circleci/node:14.15.5-browsers
    steps:
      - checkout
      - node/install-yarn
      - run: node --version
      - run: yarn --version
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn lintjs
      - run: yarn lintjsx
      - run: yarn coverage
      - codecov/upload:
          file: coverage/*.json

workflows:
  ci:
    jobs:
      - tests
